// Generated by scripts/generate-project-assets.mjs. Do not edit manually.
export const projectAssets = [
	"/projects/calmora/Page1.png",
	"/projects/calmora/page2.png",
	"/projects/calmora/Page3.png",
	"/projects/calmora/Page4.png",
	"/projects/calmora/Page5.png",
	"/projects/calmora/Page6.png",
	"/projects/entecavir/01.png",
	"/projects/entecavir/02.png",
	"/projects/entecavir/03.png",
	"/projects/entecavir/04.png",
	"/projects/entecavir/05.png",
	"/projects/Lightshadow/page1.png",
	"/projects/Lightshadow/page2.png",
	"/projects/Lightshadow/page3.png",
	"/projects/Lightshadow/page4.png",
	"/projects/Lightshadow/page5.png",
	"/projects/UI/ec5c4348053ea317671ef60edf95694b.jpg"
] as const;
